services:
  planning-control:
    image: ghcr.io/autowarefoundation/demo_packages:planning-control
    container_name: planning-control
    network_mode: "host"
    restart: always
    depends_on:
      netconfig:
        condition: service_healthy
    volumes:
      - shared_data:/root/shared
    environment:
      - ROS_DOMAIN_ID=88
      - CYCLONEDDS_URI=/root/shared/cyclonedds.xml
    command: >-
      sleep infinity
  simulator:
    image: ghcr.io/autowarefoundation/demo_packages:simulator
    container_name: simulator
    network_mode: "host"
    restart: always
    depends_on:
      netconfig:
        condition: service_healthy
    volumes:
      - shared_data:/root/shared
    environment:
      - ROS_DOMAIN_ID=88
      - CYCLONEDDS_URI=/root/shared/cyclonedds.xml
    command: >-
      sleep infinity
  netconfig:
    image: ghcr.io/autowarefoundation/demo_packages:netconfig
    container_name: netconfig
    privileged: true
    network_mode: "host"
    restart: always
    volumes:
      - shared_data:/root/shared
    healthcheck:
      test: ["CMD", "monitor_peers"]
      interval: 5m
      timeout: 1m
      retries: 5
    command: >-
      sleep infinity

volumes:
  shared_data:
    name: "shared_data"